### ISSUE TITLE
Program to automatically align a groundtruth sequence with a computed sequence (SM-DTW)

### ISSUE THREAD

**Issue by TimoWintz** [romi/plant-3d-vision#25]
Implementation of a modified "dynamical time-warping" algorithm including split/merge operations to align groundtruth sequences with computed sequences generated by our analysis pipelines.
-> takes as first input the raw "angles&internodes" sequence computed by the pipe 
-> second input is the groundtruth reference sequence
-> provide an automatized realignment and interpretation of over-segmentation (merge) and under-segmentation (split)

**In progress**: 
@cgodin generates "SM-DTW" (Split-Merge Dynamical Time Warping), an automatic alignment program (in python) for two sequences of phyllotaxis (typically a ground truth and an sequence generated from the pipe). A sequence contains two sub-sequences: one for angles and one for internodes.
@fabfabBesnard generates a program (in R) that simulates phyllotaxis sequences (angles and internodes) and also simulates segmentation errors. This will be used to test the SM-DTW program.

**Comment by fabfabBesnard** [comment]
issue closed with the repo/submodule sm-dtw integrate in plant-3d-vision from v0.10
